Repository hheyhhay/refactor-tractor-fitlit-b, pull requests merged in 2021-07, with the labels that each got.

#4 Feature/create api calls
  src/apiCalls.js
  src/scripts.js
Labels: enhancement

#7 Feature/add parent class
  src/Hydration.js
  src/Repository.js
  src/User-repo.js
  src/data/activity.js
  src/data/test-data.js
  test/Repository-test.js
  test/hydration-test.js
Labels: documentation

#8 Refactor/integrate repository methods
  src/Hydration.js
  src/Repository.js
  src/User-repo.js
  src/domUpdates.js
  src/scripts.js
  test/Repository-test.js
Labels: refactor
